//go:build acceptance

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/danabrams/gromit/internal/backlog"
	"github.com/danabrams/gromit/internal/config"
	"github.com/danabrams/gromit/internal/pipeline"
)

// TestPipelineRefinePrompt_WithEpicContext tests that buildRefinePrompt includes epic context when appropriate
func TestPipelineRefinePrompt_WithEpicContext(t *testing.T) {
	// Expected failure: pipeline.buildRefinePrompt does not yet detect epics or inject epic context
	// Expected behavior: When a backlog item references an epic via context field,
	// buildRefinePrompt should detect it and include epic document + sibling specs
	//
	// This test verifies acceptance criteria:
	// 1. When backlog context contains known epic ID, prompt includes full epic document and sibling spec summaries
	// 4. Prompt instructs Claude to set epic: <id> in frontmatter
	// 5. Detection handles substring matching

	tmpDir := t.TempDir()
	gromitDir := filepath.Join(tmpDir, ".gromit")
	epicsDir := filepath.Join(gromitDir, "epics")
	specsDir := filepath.Join(gromitDir, "specs")

	if err := os.MkdirAll(epicsDir, 0755); err != nil {
		t.Fatalf("Failed to create epics dir: %v", err)
	}
	if err := os.MkdirAll(specsDir, 0755); err != nil {
		t.Fatalf("Failed to create specs dir: %v", err)
	}

	// Create epic file
	epicContent := `---
epic_id: payment-integration
created: 2026-02-11
---

# Payment Integration Epic

This epic covers all payment processing features.

## Vision

Enable multiple payment methods for customers.
`
	epicPath := filepath.Join(epicsDir, "payment.md")
	if err := os.WriteFile(epicPath, []byte(epicContent), 0644); err != nil {
		t.Fatalf("Failed to write epic file: %v", err)
	}

	// Create sibling spec
	siblingContent := `---
id: payment-api
epic: payment-integration
created: 2026-02-11
---

# Payment API Spec

## Acceptance Criteria

- API accepts payment requests
- API returns transaction ID on success
`
	siblingPath := filepath.Join(specsDir, "payment-api.md")
	if err := os.WriteFile(siblingPath, []byte(siblingContent), 0644); err != nil {
		t.Fatalf("Failed to write sibling spec: %v", err)
	}

	// Create backlog with idea referencing epic
	bf, err := backlog.NewFile(gromitDir)
	if err != nil {
		t.Fatalf("Failed to create backlog file: %v", err)
	}

	idea := &backlog.Idea{
		ID:      "idea-test-1",
		Text:    "Add payment confirmation page",
		Type:    "feature",
		Context: "Part of payment-integration epic",
		Status:  "pending",
	}
	if err := bf.Add(idea); err != nil {
		t.Fatalf("Failed to add idea: %v", err)
	}

	// Create pipeline
	cfg := &config.Config{
		Paths: config.PathsConfig{
			GromitDir: gromitDir,
			Specs:     specsDir,
		},
	}

	mockAgent := &mockAgentForPromptTest{}
	mockResolver := &mockResolverForPromptTest{agent: mockAgent}
	mockBacklog := &backlogAdapterForTest{file: bf}

	deps := &pipeline.Deps{
		AgentResolver: mockResolver,
		BacklogClient: mockBacklog,
	}

	paths := &pipeline.Paths{
		GromitDir: gromitDir,
		SpecsDir:  specsDir,
	}

	p := pipeline.New(deps, paths)

	// Load idea with context
	loadedIdea, err := bf.Get("idea-test-1")
	if err != nil {
		t.Fatalf("Failed to load idea: %v", err)
	}

	ideaText := loadedIdea.Text
	if loadedIdea.Context != "" {
		ideaText = loadedIdea.Text + "\n\nContext: " + loadedIdea.Context
	}

	// Build the prompt using the pipeline's internal buildRefinePrompt method
	// Since it's private, we need to invoke it indirectly by calling a method that uses it
	// The Refine method calls buildRefinePrompt internally and passes it to the agent
	// We can capture what prompt was generated by checking what the mock agent received

	input := pipeline.RefineInput{
		IdeaID: "idea-test-1",
	}

	// Call Refine - it will invoke buildRefinePrompt and pass prompt to agent
	_, err = p.Refine(t.Context(), input)
	// We expect an error because our mock agent doesn't actually do anything
	// but we can still check what prompt it received

	// Get the prompt that was passed to the agent
	prompt := mockAgent.receivedPromptPath
	if prompt == "" {
		t.Fatal("No prompt was passed to agent")
	}

	// Read the prompt file
	promptContent, err := os.ReadFile(prompt)
	if err != nil {
		t.Fatalf("Failed to read prompt file: %v", err)
	}
	promptStr := string(promptContent)

	// Verify epic context section is present
	if !strings.Contains(promptStr, "## Epic Context") {
		t.Error("Prompt should contain '## Epic Context' section header")
	}

	// Verify epic document content is included
	if !strings.Contains(promptStr, "# Payment Integration Epic") {
		t.Error("Prompt should contain epic title from document")
	}
	if !strings.Contains(promptStr, "Enable multiple payment methods for customers") {
		t.Error("Prompt should contain epic vision from document")
	}

	// Verify frontmatter instruction
	if !strings.Contains(promptStr, "Include `epic: payment-integration` in the spec frontmatter") {
		t.Error("Prompt should instruct Claude to add epic field to frontmatter")
	}

	// Verify sibling specs section
	if !strings.Contains(promptStr, "### Sibling Specs") {
		t.Error("Prompt should contain '### Sibling Specs' section")
	}

	// Verify sibling spec is summarized
	if !strings.Contains(promptStr, "**Payment API Spec**") {
		t.Error("Prompt should contain sibling spec title")
	}
	if !strings.Contains(promptStr, "(`payment-api`)") {
		t.Error("Prompt should contain sibling spec ID")
	}
	if !strings.Contains(promptStr, "API accepts payment requests") {
		t.Error("Prompt should contain sibling acceptance criteria")
	}
	if !strings.Contains(promptStr, "API returns transaction ID on success") {
		t.Error("Prompt should contain sibling acceptance criteria")
	}

	// Verify epic section appears between idea and specs directory
	ideaIndex := strings.Index(promptStr, "Add payment confirmation page")
	epicIndex := strings.Index(promptStr, "## Epic Context")
	specsIndex := strings.Index(promptStr, "Specs directory:")

	if ideaIndex == -1 || epicIndex == -1 || specsIndex == -1 {
		t.Fatal("Prompt missing required sections for ordering check")
	}

	if !(ideaIndex < epicIndex && epicIndex < specsIndex) {
		t.Error("Epic Context section should appear between idea text and specs directory line")
	}
}

// TestPipelineRefinePrompt_WithoutEpicContext tests that buildRefinePrompt works normally without epic
func TestPipelineRefinePrompt_WithoutEpicContext(t *testing.T) {
	// Expected failure: pipeline.buildRefinePrompt doesn't distinguish epic vs non-epic cases yet
	// Expected behavior: When no epic is detected, prompt should match current behavior (no epic section)
	//
	// This test verifies acceptance criterion:
	// 2. When no epic ID matches, the refine prompt is unchanged from current behavior

	tmpDir := t.TempDir()
	gromitDir := filepath.Join(tmpDir, ".gromit")
	epicsDir := filepath.Join(gromitDir, "epics")
	specsDir := filepath.Join(gromitDir, "specs")

	if err := os.MkdirAll(epicsDir, 0755); err != nil {
		t.Fatalf("Failed to create epics dir: %v", err)
	}
	if err := os.MkdirAll(specsDir, 0755); err != nil {
		t.Fatalf("Failed to create specs dir: %v", err)
	}

	// Create an epic but don't reference it
	epicContent := `---
epic_id: unrelated-epic
created: 2026-02-11
---

# Unrelated Epic
`
	epicPath := filepath.Join(epicsDir, "unrelated.md")
	if err := os.WriteFile(epicPath, []byte(epicContent), 0644); err != nil {
		t.Fatalf("Failed to write epic file: %v", err)
	}

	// Create backlog with idea NOT referencing any epic
	bf, err := backlog.NewFile(gromitDir)
	if err != nil {
		t.Fatalf("Failed to create backlog file: %v", err)
	}

	idea := &backlog.Idea{
		ID:      "idea-test-2",
		Text:    "Add user profile editing",
		Type:    "feature",
		Context: "Standalone feature not part of any epic",
		Status:  "pending",
	}
	if err := bf.Add(idea); err != nil {
		t.Fatalf("Failed to add idea: %v", err)
	}

	// Create pipeline
	mockAgent := &mockAgentForPromptTest{}
	mockResolver := &mockResolverForPromptTest{agent: mockAgent}
	mockBacklog := &backlogAdapterForTest{file: bf}

	deps := &pipeline.Deps{
		AgentResolver: mockResolver,
		BacklogClient: mockBacklog,
	}

	paths := &pipeline.Paths{
		GromitDir: gromitDir,
		SpecsDir:  specsDir,
	}

	p := pipeline.New(deps, paths)

	input := pipeline.RefineInput{
		IdeaID: "idea-test-2",
	}

	_, _ = p.Refine(t.Context(), input)

	// Get the prompt that was passed to the agent
	prompt := mockAgent.receivedPromptPath
	if prompt == "" {
		t.Fatal("No prompt was passed to agent")
	}

	// Read the prompt file
	promptContent, err := os.ReadFile(prompt)
	if err != nil {
		t.Fatalf("Failed to read prompt file: %v", err)
	}
	promptStr := string(promptContent)

	// Verify NO epic context section
	if strings.Contains(promptStr, "## Epic Context") {
		t.Error("Prompt should NOT contain '## Epic Context' section when no epic is detected")
	}

	// Verify NO epic document content
	if strings.Contains(promptStr, "### Epic Document") {
		t.Error("Prompt should NOT contain '### Epic Document' section when no epic is detected")
	}

	// Verify NO sibling specs section
	if strings.Contains(promptStr, "### Sibling Specs") {
		t.Error("Prompt should NOT contain '### Sibling Specs' section when no epic is detected")
	}

	// Verify standard prompt structure remains
	if !strings.Contains(promptStr, "Add user profile editing") {
		t.Error("Prompt should still contain the idea text")
	}
	if !strings.Contains(promptStr, "Specs directory:") {
		t.Error("Prompt should still contain specs directory line")
	}
}

// TestPipelineRefinePrompt_BlankSession tests that blank sessions skip epic detection
func TestPipelineRefinePrompt_BlankSession(t *testing.T) {
	// Expected failure: blank session handling needs to skip epic detection
	// Expected behavior: Blank sessions (no idea text/ID) skip epic detection entirely
	//
	// This test verifies that ad-hoc ideas and blank sessions skip epic detection
	// as mentioned in the task description.

	tmpDir := t.TempDir()
	gromitDir := filepath.Join(tmpDir, ".gromit")
	epicsDir := filepath.Join(gromitDir, "epics")
	specsDir := filepath.Join(gromitDir, "specs")

	if err := os.MkdirAll(epicsDir, 0755); err != nil {
		t.Fatalf("Failed to create epics dir: %v", err)
	}
	if err := os.MkdirAll(specsDir, 0755); err != nil {
		t.Fatalf("Failed to create specs dir: %v", err)
	}

	// Create an epic
	epicContent := `---
epic_id: test-epic
created: 2026-02-11
---

# Test Epic
`
	epicPath := filepath.Join(epicsDir, "test.md")
	if err := os.WriteFile(epicPath, []byte(epicContent), 0644); err != nil {
		t.Fatalf("Failed to write epic file: %v", err)
	}

	// Create pipeline with blank session (no idea text or ID)
	mockAgent := &mockAgentForPromptTest{}
	mockResolver := &mockResolverForPromptTest{agent: mockAgent}
	mockBacklog := &backlogAdapterForTest{}

	deps := &pipeline.Deps{
		AgentResolver: mockResolver,
		BacklogClient: mockBacklog,
	}

	paths := &pipeline.Paths{
		GromitDir: gromitDir,
		SpecsDir:  specsDir,
	}

	p := pipeline.New(deps, paths)

	input := pipeline.RefineInput{
		// Empty - blank session
	}

	_, _ = p.Refine(t.Context(), input)

	// Get the prompt
	prompt := mockAgent.receivedPromptPath
	if prompt == "" {
		t.Fatal("No prompt was passed to agent")
	}

	promptContent, err := os.ReadFile(prompt)
	if err != nil {
		t.Fatalf("Failed to read prompt file: %v", err)
	}
	promptStr := string(promptContent)

	// Verify NO epic context
	if strings.Contains(promptStr, "## Epic Context") {
		t.Error("Blank session prompt should NOT contain epic context")
	}

	// Verify standard blank session structure
	if !strings.Contains(promptStr, "Specs directory:") {
		t.Error("Blank session prompt should contain specs directory")
	}
}

// TestPipelineRefinePrompt_AdHocIdea tests that ad-hoc ideas skip epic detection
func TestPipelineRefinePrompt_AdHocIdea(t *testing.T) {
	// Expected failure: ad-hoc idea handling needs to skip epic detection
	// Expected behavior: Ad-hoc ideas (direct text input, not from backlog) skip epic detection
	//
	// This test verifies that when users provide ad-hoc idea text,
	// no epic detection occurs even if the text contains epic ID strings.

	tmpDir := t.TempDir()
	gromitDir := filepath.Join(tmpDir, ".gromit")
	epicsDir := filepath.Join(gromitDir, "epics")
	specsDir := filepath.Join(gromitDir, "specs")

	if err := os.MkdirAll(epicsDir, 0755); err != nil {
		t.Fatalf("Failed to create epics dir: %v", err)
	}
	if err := os.MkdirAll(specsDir, 0755); err != nil {
		t.Fatalf("Failed to create specs dir: %v", err)
	}

	// Create an epic
	epicContent := `---
epic_id: payment-integration
created: 2026-02-11
---

# Payment Integration Epic
`
	epicPath := filepath.Join(epicsDir, "payment.md")
	if err := os.WriteFile(epicPath, []byte(epicContent), 0644); err != nil {
		t.Fatalf("Failed to write epic file: %v", err)
	}

	// Create pipeline with ad-hoc text that mentions epic ID
	mockAgent := &mockAgentForPromptTest{}
	mockResolver := &mockResolverForPromptTest{agent: mockAgent}
	mockBacklog := &backlogAdapterForTest{}

	deps := &pipeline.Deps{
		AgentResolver: mockResolver,
		BacklogClient: mockBacklog,
	}

	paths := &pipeline.Paths{
		GromitDir: gromitDir,
		SpecsDir:  specsDir,
	}

	p := pipeline.New(deps, paths)

	input := pipeline.RefineInput{
		IdeaText: "Implement payment-integration feature for checkout",
	}

	_, _ = p.Refine(t.Context(), input)

	// Get the prompt
	prompt := mockAgent.receivedPromptPath
	if prompt == "" {
		t.Fatal("No prompt was passed to agent")
	}

	promptContent, err := os.ReadFile(prompt)
	if err != nil {
		t.Fatalf("Failed to read prompt file: %v", err)
	}
	promptStr := string(promptContent)

	// Verify NO epic context (because it's ad-hoc, not from backlog)
	if strings.Contains(promptStr, "## Epic Context") {
		t.Error("Ad-hoc idea prompt should NOT contain epic context even if text mentions epic ID")
	}

	// Verify idea text is present
	if !strings.Contains(promptStr, "payment-integration feature for checkout") {
		t.Error("Prompt should contain the ad-hoc idea text")
	}
}

// Mock types for testing

type mockAgentForPromptTest struct {
	receivedPromptPath string
}

func (m *mockAgentForPromptTest) Launch(promptPath string) error {
	m.receivedPromptPath = promptPath
	return nil
}

type mockResolverForPromptTest struct {
	agent *mockAgentForPromptTest
}

func (m *mockResolverForPromptTest) Resolve(phase string, flagOverride string, choosePicker bool) (pipeline.Agent, error) {
	return m.agent, nil
}

type backlogAdapterForTest struct {
	file *backlog.File
}

func (b *backlogAdapterForTest) List() ([]*pipeline.Idea, error) {
	if b.file == nil {
		return []*pipeline.Idea{}, nil
	}
	ideas, err := b.file.List()
	if err != nil {
		return nil, err
	}
	result := make([]*pipeline.Idea, len(ideas))
	for i, idea := range ideas {
		result[i] = &pipeline.Idea{
			ID:       idea.ID,
			Text:     idea.Text,
			Type:     idea.Type,
			Context:  idea.Context,
			Status:   idea.Status,
			SpecName: idea.SpecName,
		}
	}
	return result, nil
}

func (b *backlogAdapterForTest) Get(id string) (*pipeline.Idea, error) {
	if b.file == nil {
		return nil, nil
	}
	idea, err := b.file.Get(id)
	if err != nil || idea == nil {
		return nil, err
	}
	return &pipeline.Idea{
		ID:       idea.ID,
		Text:     idea.Text,
		Type:     idea.Type,
		Context:  idea.Context,
		Status:   idea.Status,
		SpecName: idea.SpecName,
	}, nil
}

func (b *backlogAdapterForTest) Add(item *pipeline.Idea) error {
	if b.file == nil {
		return nil
	}
	return b.file.Add(&backlog.Idea{
		ID:       item.ID,
		Text:     item.Text,
		Type:     item.Type,
		Context:  item.Context,
		Status:   item.Status,
		SpecName: item.SpecName,
	})
}

func (b *backlogAdapterForTest) Update(id string, fn func(*pipeline.Idea)) error {
	if b.file == nil {
		return nil
	}
	return b.file.Update(id, func(idea *backlog.Idea) {
		pipelineIdea := &pipeline.Idea{
			ID:       idea.ID,
			Text:     idea.Text,
			Type:     idea.Type,
			Context:  idea.Context,
			Status:   idea.Status,
			SpecName: idea.SpecName,
		}
		fn(pipelineIdea)
		idea.Status = pipelineIdea.Status
		idea.SpecName = pipelineIdea.SpecName
	})
}
