package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/danabrams/gromit/internal/next/runstore"
)

// tierOverrideResult represents the distillation output for tier override assertions.
type tierOverrideResult struct {
	RunID     string                `json:"run_id"`
	SpecID    string                `json:"spec_id"`
	Outcome   string                `json:"outcome"`
	ModelTier string                `json:"model_tier"`
	Summary   string                `json:"summary"`
	Proposals []tierOverrideProposal `json:"proposals"`
	CreatedAt time.Time             `json:"created_at"`
	Metadata  map[string]string     `json:"metadata,omitempty"`
}

type tierOverrideProposal struct {
	ID                  string   `json:"id"`
	Type                string   `json:"type"`
	Title               string   `json:"title"`
	Content             string   `json:"content,omitempty"`
	Confidence          float64  `json:"confidence,omitempty"`
	ConfidenceRationale string   `json:"confidence_rationale,omitempty"`
	EvidenceReferences  []string `json:"evidence_references,omitempty"`
}

func TestScenario_StandaloneDistillRerunsWithTierOverride(t *testing.T) {
	// === Seed ===
	tmp := t.TempDir()
	store := runstore.NewStore(tmp)

	run := &runstore.RunState{
		RunID:                 "run-106",
		SpecID:                "spec-refactor-auth",
		ProjectID:             "fixture-app",
		Status:                runstore.StatusReadyForReview,
		StartedAt:             time.Date(2026, 3, 18, 9, 0, 0, 0, time.UTC),
		EndedAt:               time.Date(2026, 3, 18, 9, 12, 0, 0, time.UTC),
		FinalValidationPassed: true,
		FinalReviewPassed:     true,
		FinalAcceptancePassed: true,
		Tasks: []runstore.Task{
			{TaskID: "task-1", Status: "done", ModelTier: "sonnet"},
			{TaskID: "task-2", Status: "done", ModelTier: "sonnet"},
		},
	}
	if err := store.Save(run); err != nil {
		t.Fatalf("save run: %v", err)
	}

	evidenceDir := store.RunEvidenceDir("run-106")
	if err := os.MkdirAll(evidenceDir, 0o755); err != nil {
		t.Fatalf("mkdir evidence: %v", err)
	}

	// Seed review-outcome.json (prerequisite for distillation)
	reviewOutcome := map[string]interface{}{
		"run_id":      "run-106",
		"outcome":     "accepted",
		"summary":     "Auth refactor looks good, all checks pass",
		"reviewed_at": "2026-03-18T09:20:00Z",
		"manual_results": []map[string]string{
			{"id": "check-auth-flow", "result": "pass"},
			{"id": "check-session-mgmt", "result": "pass"},
		},
	}
	writeJSON(t, filepath.Join(evidenceDir, "review-outcome.json"), reviewOutcome)

	// Seed existing distillation-proposals.json from prior automatic distillation (sonnet tier)
	priorResult := tierOverrideResult{
		RunID:     "run-106",
		SpecID:    "spec-refactor-auth",
		Outcome:   "accepted",
		ModelTier: "sonnet",
		Summary:   "Prior automatic distillation with sonnet tier",
		CreatedAt: time.Date(2026, 3, 18, 9, 25, 0, 0, time.UTC),
		Metadata: map[string]string{
			"run_id":  "run-106",
			"spec_id": "spec-refactor-auth",
			"model":   "sonnet",
		},
		Proposals: []tierOverrideProposal{
			{
				ID:                  "run-106-doctrine_rule-1",
				Type:                "doctrine_rule",
				Title:               "Old proposal from sonnet distillation",
				Content:             "This proposal was generated by the prior sonnet-tier distillation",
				Confidence:          0.70,
				ConfidenceRationale: "Lower confidence from sonnet tier",
			},
		},
	}
	priorJSON, err := json.MarshalIndent(priorResult, "", "  ")
	if err != nil {
		t.Fatalf("marshal prior result: %v", err)
	}
	proposalsPath := filepath.Join(evidenceDir, "distillation-proposals.json")
	if err := os.WriteFile(proposalsPath, priorJSON, 0o644); err != nil {
		t.Fatalf("write prior distillation-proposals.json: %v", err)
	}

	// Seed existing distillation-proposals.md from prior automatic distillation
	priorMD := "# Distillation Proposals\n\n**Run:** run-106 | **Outcome:** accepted | **Model:** sonnet\n\n## Summary\n\nPrior automatic distillation with sonnet tier\n"
	markdownPath := filepath.Join(evidenceDir, "distillation-proposals.md")
	if err := os.WriteFile(markdownPath, []byte(priorMD), 0o644); err != nil {
		t.Fatalf("write prior distillation-proposals.md: %v", err)
	}

	// Verify prior files exist with sonnet tier
	priorRaw, err := os.ReadFile(proposalsPath)
	if err != nil {
		t.Fatalf("read prior proposals: %v", err)
	}
	if !strings.Contains(string(priorRaw), `"model_tier": "sonnet"`) {
		t.Fatal("precondition: prior proposals should have model_tier sonnet")
	}

	// === Invoke ===
	// Simulate `gromit-next review distill --run run-106 --tier high`
	// Re-run distillation with high tier override. (Will be replaced by actual
	// distiller call once the reviewdistiller package lands on main.)
	now := time.Now().UTC()
	newResult := tierOverrideResult{
		RunID:     "run-106",
		SpecID:    "spec-refactor-auth",
		Outcome:   "accepted",
		ModelTier: "high",
		Summary:   "High-tier distillation provides deeper analysis of auth refactor patterns",
		CreatedAt: now,
		Metadata: map[string]string{
			"run_id":  "run-106",
			"spec_id": "spec-refactor-auth",
			"model":   "high",
		},
		Proposals: []tierOverrideProposal{
			{
				ID:                  fmt.Sprintf("run-106-doctrine_rule-%d", 1),
				Type:                "doctrine_rule",
				Title:               "Enforce session token rotation on auth refactors",
				Content:             "Any auth refactor must include session token rotation validation to prevent stale session attacks",
				Confidence:          0.94,
				ConfidenceRationale: "High-tier analysis identified security pattern from accepted auth changes",
				EvidenceReferences:  []string{"review-outcome.json", "check-auth-flow"},
			},
			{
				ID:                  fmt.Sprintf("run-106-planner_heuristic-%d", 2),
				Type:                "planner_heuristic",
				Title:               "Decompose auth tasks by middleware layer",
				Content:             "When refactoring auth, plan separate tasks for session management, token validation, and middleware wiring",
				Confidence:          0.91,
				ConfidenceRationale: "High-tier analysis of task structure shows layer-based decomposition reduces rework",
				EvidenceReferences:  []string{"review-outcome.json"},
			},
			{
				ID:                  fmt.Sprintf("run-106-doctrine_rule-%d", 3),
				Type:                "doctrine_rule",
				Title:               "Require integration tests for auth middleware changes",
				Content:             "Auth middleware changes must be covered by integration tests, not just unit tests",
				Confidence:          0.89,
				ConfidenceRationale: "High-tier cross-referencing of test coverage with acceptance criteria",
				EvidenceReferences:  []string{"review-outcome.json", "check-session-mgmt"},
			},
			{
				ID:                  fmt.Sprintf("run-106-info-%d", 4),
				Type:                "info",
				Title:               "Auth refactor cost-benefit observation",
				Content:             "Splitting auth refactoring across two tasks reduced cycle count compared to monolithic auth changes",
				Confidence:          0.85,
				ConfidenceRationale: "Comparison with prior auth-related runs at high tier analysis depth",
			},
		},
	}

	// Overwrite distillation-proposals.json with new high-tier result
	newJSON, err := json.MarshalIndent(newResult, "", "  ")
	if err != nil {
		t.Fatalf("marshal new result: %v", err)
	}
	if err := os.WriteFile(proposalsPath, newJSON, 0o644); err != nil {
		t.Fatalf("write distillation-proposals.json: %v", err)
	}

	// Overwrite distillation-proposals.md with new high-tier rendering
	var mdBuf strings.Builder
	fmt.Fprintf(&mdBuf, "# Distillation Proposals\n\n")
	fmt.Fprintf(&mdBuf, "**Run:** %s | **Outcome:** %s | **Model:** %s\n\n", newResult.RunID, newResult.Outcome, newResult.ModelTier)
	fmt.Fprintf(&mdBuf, "## Summary\n\n%s\n\n", newResult.Summary)
	for i, p := range newResult.Proposals {
		fmt.Fprintf(&mdBuf, "### %d. [%s] %s\n\n", i+1, p.Type, p.Title)
		fmt.Fprintf(&mdBuf, "%s\n\n", p.Content)
		fmt.Fprintf(&mdBuf, "**Confidence:** %.2f — %s\n\n", p.Confidence, p.ConfidenceRationale)
		if len(p.EvidenceReferences) > 0 {
			fmt.Fprintf(&mdBuf, "**Evidence:** %s\n\n", strings.Join(p.EvidenceReferences, ", "))
		}
	}
	if err := os.WriteFile(markdownPath, []byte(mdBuf.String()), 0o644); err != nil {
		t.Fatalf("write distillation-proposals.md: %v", err)
	}

	// === Assert ===

	// 1. distillation-proposals.json exists and is parseable
	rawJSON, err := os.ReadFile(proposalsPath)
	if err != nil {
		t.Fatalf("read distillation-proposals.json: %v", err)
	}
	var parsed tierOverrideResult
	if err := json.Unmarshal(rawJSON, &parsed); err != nil {
		t.Fatalf("parse distillation-proposals.json: %v", err)
	}

	// 2. run_id is "run-106"
	if parsed.RunID != "run-106" {
		t.Errorf("expected run_id 'run-106', got %q", parsed.RunID)
	}

	// 3. model_tier reflects "high" (the override), not "sonnet" (the prior tier)
	if parsed.ModelTier != "high" {
		t.Errorf("expected model_tier 'high' after tier override, got %q", parsed.ModelTier)
	}

	// 4. Prior sonnet tier is no longer present
	jsonStr := string(rawJSON)
	if strings.Contains(jsonStr, `"model_tier": "sonnet"`) {
		t.Error("distillation-proposals.json should not contain prior sonnet model_tier after override")
	}

	// 5. Outcome is still "accepted"
	if parsed.Outcome != "accepted" {
		t.Errorf("expected outcome 'accepted', got %q", parsed.Outcome)
	}

	// 6. CreatedAt is non-zero and newer than the prior distillation
	if parsed.CreatedAt.IsZero() {
		t.Error("expected non-zero created_at")
	}
	priorCreatedAt := time.Date(2026, 3, 18, 9, 25, 0, 0, time.UTC)
	if !parsed.CreatedAt.After(priorCreatedAt) {
		t.Errorf("expected created_at after prior distillation (%v), got %v", priorCreatedAt, parsed.CreatedAt)
	}

	// 7. New proposals are present (not the old single proposal from sonnet)
	if len(parsed.Proposals) < 3 || len(parsed.Proposals) > 5 {
		t.Errorf("expected 3-5 proposals from high-tier distillation, got %d", len(parsed.Proposals))
	}

	// 8. Old sonnet proposal title is gone
	for _, p := range parsed.Proposals {
		if strings.Contains(p.Title, "Old proposal from sonnet") {
			t.Error("expected prior sonnet proposals to be overwritten, found old proposal title")
		}
	}

	// 9. At least one doctrine_rule or planner_heuristic in new proposals
	hasReinforcementType := false
	for _, p := range parsed.Proposals {
		if p.Type == "doctrine_rule" || p.Type == "planner_heuristic" {
			hasReinforcementType = true
			break
		}
	}
	if !hasReinforcementType {
		types := make([]string, len(parsed.Proposals))
		for i, p := range parsed.Proposals {
			types[i] = p.Type
		}
		t.Errorf("expected at least one doctrine_rule or planner_heuristic, got types: %v", types)
	}

	// 10. Each proposal has required schema fields populated
	for i, p := range parsed.Proposals {
		if p.ID == "" {
			t.Errorf("proposal[%d]: expected non-empty ID", i)
		}
		if p.Type == "" {
			t.Errorf("proposal[%d]: expected non-empty Type", i)
		}
		if p.Title == "" {
			t.Errorf("proposal[%d]: expected non-empty Title", i)
		}
		if p.Content == "" {
			t.Errorf("proposal[%d]: expected non-empty Content", i)
		}
		if p.Confidence == 0 {
			t.Errorf("proposal[%d]: expected non-zero Confidence", i)
		}
		if p.ConfidenceRationale == "" {
			t.Errorf("proposal[%d]: expected non-empty ConfidenceRationale", i)
		}
	}

	// 11. Metadata reflects high tier
	if parsed.Metadata["model"] != "high" {
		t.Errorf("expected metadata model 'high', got %q", parsed.Metadata["model"])
	}

	// 12. distillation-proposals.md was overwritten and reflects high tier
	mdData, err := os.ReadFile(markdownPath)
	if err != nil {
		t.Fatalf("read distillation-proposals.md: %v", err)
	}
	if len(mdData) == 0 {
		t.Error("expected non-empty distillation-proposals.md")
	}

	mdStr := string(mdData)

	// 13. Markdown contains "high" model reference, not "sonnet"
	if !strings.Contains(mdStr, "**Model:** high") {
		t.Error("distillation-proposals.md should reference Model: high")
	}
	if strings.Contains(mdStr, "**Model:** sonnet") {
		t.Error("distillation-proposals.md should not reference prior sonnet model")
	}

	// 14. Markdown contains new summary, not old
	if strings.Contains(mdStr, "Prior automatic distillation") {
		t.Error("distillation-proposals.md should not contain prior distillation summary")
	}
	if !strings.Contains(mdStr, "High-tier distillation") {
		t.Error("distillation-proposals.md should contain new high-tier summary")
	}

	// 15. Markdown contains new proposal titles
	if !strings.Contains(mdStr, "session token rotation") {
		t.Error("distillation-proposals.md should contain new proposal content about session token rotation")
	}

	// 16. Markdown mentions the outcome
	if !strings.Contains(mdStr, "accepted") {
		t.Error("distillation-proposals.md should mention accepted outcome")
	}
}